import { Injectable } from '@angular/core';
import { AngularFirestore, AngularFirestoreCollection, AngularFirestoreDocument } from '@angular/fire/compat/firestore';
import { Observable } from 'rxjs';
import { AuthService } from 'src/app/auth/auth.service';
import { UserLibraryData } from 'src/app/shared/streaming-data.model';
import { map } from 'rxjs/operators'

@Injectable({
  providedIn: 'root'
})
export class UserLibraryService {
  watchlistCollection: AngularFirestoreCollection; // need to specificy <type>
  watchlist: Observable<UserLibraryData[]>
  movieDoc: AngularFirestoreDocument<UserLibraryData>; //for delteting indv. movie doc



  constructor(
    private authService: AuthService,
    public afs: AngularFirestore
  ) {
    // set Firestore route for logged in User's Library Database
    this.watchlistCollection = this.afs
      .collection('users')
      .doc(this.authService.userData.uid)
      .collection('watchlist')

    // retrieve all projcts form the database when component is loaded
    this.watchlist = this.watchlistCollection
      .snapshotChanges()
      .pipe(
        map(changes => changes.map(a => {
          const data = a.payload.doc.data() as UserLibraryData //show unique ID generated by firestore when data is created
          data.id = a.payload.doc.id;
          return data
      }))
    )
  }


  // Add movie/show to User->Watchlist in Firestore
  addToWatchlist(movie: UserLibraryData) {
    // have to declare below to prevent "firestore custom Obj error"
    const watchlistData: UserLibraryData = {
      titleName: movie.titleName,
      streamName: movie.streamName,
      watched: false
    }
    this.watchlistCollection
      .add(watchlistData)
      .then((dataAdded) => {
        watchlistData.id = dataAdded.id; //assign firebase created ID to watchlist obj ID
        console.log('added to firestore:', watchlistData.id)
        window.alert(watchlistData.titleName +  ' was added to your library')
      })
      .catch((error) => {
      console.log('Error adding document to firestore:', error)
    })
  }

  getWatchlist() {
    return this.watchlist;
  }

  removeFromWatchlist(movie) {
    console.log(movie.id)
    this.movieDoc = this.watchlistCollection.doc(movie.id)
    console.log('movie doc:', this.movieDoc)
    this.movieDoc.delete();
    // this.projectDoc = this.afs.doc()
  }

  // update 'watched' field of the watchlist doc in firestore (true or false)
  updateIfWatched(movie, watched: boolean) {
    this.movieDoc = this.watchlistCollection.doc(movie.id);
    this.movieDoc.update({"watched": watched})
  }



}
